### ISSUE TITLE
[rfe] ability to restore configuration from backup

### ISSUE THREAD

**Issue by jnpkrn** [pbrezina/authselect#120]
At least it was my assumption that I could go conveniently back when
newly activated profile doesn't work as expected.

Could something like `rewind NAME` work here?

**Comment by sej7278** [comment]
```authselect select sssd``` sort of does that, if you can remember what the default values were for ```with-faillock``` and ```without-nullok``` were.

the defaults are stored in /usr/share/authselect/default/sssd/ so you could copy them back and the symlinks in /etc/pam.d/ would be ok.

oddly enough ```dnf reinstall authselect``` (or yum) doesn't do anything to the config files either - in fact if you move /etc/authselect a reinstall doesn't put anything back - is that a RHEL8 bug?

**Comment by jnpkrn** [comment]
Hm, I'm not sure we mean the same.

What I've meant:

  1. I install authselect to already configured deployment, decide
     to switch to some profile making a backup `orig`, will figure
     out it is not working out as I expected, want to switch back,
     `authselect rewind orig` is what I envision would help me in
     that situation
  
  2. similarly, I have some sane settings, will manually tweak it
     (despite it's frowned upon IIUIC), my tweaks work well,
     newly selected profile not so much, hence I want to return
     to what's in the backup...

**Comment by sej7278** [comment]
1. installing authselect on an already configured deployment is a bit weird - you mean one setup using just vanilla pam or authconfig? that's going to be interesting. not sure if that's even possible/practical - what distro would have authselect+sssd as a bolt-on rather than install-time requirement?

2. your best bet is making a custom profile lets say "stable", then making another one based on it to play with lets call "devel".....

```
authselect create-profile stable -b sssd
authselect create-profile devel -b custom/stable
```

once you've messed up devel you just switch back to stable, delete devel and recreate it for further playing, although i'd be tempted to use git instead....

```
authselect select custom/stable
rm -rf /etc/authselect/custom/devel
authselect create-profile devel -b custom/stable
```

**Comment by pbrezina** [comment]
About installing authselect  on already configured system - authselect installation does not itself change configuration. You still must call authselect in order to configure the system with it.

About backups
1. backups are automatically created when you go from a non-authselect configuration to authselect profile, these are stored at `/var/lib/authselect/backups`. There is currently no command for that, but you can copy them manually.

2. If you modified authselect profile, applied changes and then want to go back, the backup is not created manually (you must specify `--backup`).

Which one do you hit?

**Comment by jnpkrn** [comment]
Re 1.:

> installing authselect on an already configured deployment is a bit
> weird - you mean one setup using just vanilla pam or authconfig?
> that's going to be interesting. not sure if that's even
> possible/practical 

On Fedora, similar circumstance is `dnf remove -y authselect` away.

> There is currently no command for that, but you can copy them
> manually.

I suppose "that" ~ "restoring from such backup"; if so, that's
exactly why I am asking for such a command to be considered.


Re 2.:

Yes, I see that doing things properly may be more rewarding in the
long run, but let's not forget not everyone will or want to follow
the "protocol", hence once there's a backup created already, why to
leave the user second-guessing where the originals belong to when
`authselect` knows it very well, especially when the name of the
backup is already `authselect`'s specific abstraction?

> If you modified authselect profile, applied changes and then
> want to go back, the backup is not created manually (you must
> specify --backup).

Yes, and user that used that intentionally to surely have a way
to go back is left wondering about how to restore if that turns
out to be a best fallback mode.

**Comment by pbrezina** [comment]
Restoring non-authselect configuration is simple. It is harder to restore authselect configuration but I have some ideas. Let me think about it for some time and I will come back to you. We will do this for authselect-1.1.

**Comment by pbrezina** [comment]
[Design document.](https://github.com/pbrezina/authselect/wiki/Design-Document:-Restoring-configuration-from-backup)

**Comment by pbrezina** [comment]
* `master`
  * 8f3d880991dfd73d63f58bd82452d0a8e913eabe - man: set keep threshold of transaltions to 70%
  * c2373fd9b5f20a353b393b53b5ff2303b27c25c2 - po: add CLI_TOOL_DELIMITER keyword
  * 3b1263c0a015142a0b3b947e6be00ebcbc949642 - po: update file list
  * 3e2e51df4d145daed2ed9b57ebec468cde2ddd52 - cli: support backup for apply-changes, enable-feature and disable-feature
  * e7a5778afed56c3f014175f7bbf680ba81b7a585 - cli: add backup-restore command
  * edd7226acdca01eff8cf4d16ce40d11c78119c4b - cli: add backup-remove command
  * 271ca635b3f69b3aaf1291061b0eeabe2cc5faeb - cli: add backup-list command
  * bd8b354682c423f550a1242c94920170a8e3a8fa - lib: sort backup by creation time
  * 097295bc22ca533afdf980d384ba5b46e749692d - lib: fix file_get_basename for path without directory
  * 39b593644ea5e7d592332d279bbcdad7389bdbd6 - lib: add restore ability
  * 63979c3b19d27c63c6d8dab629938408439c1b53 - lib: make selinux_get_default_context static
  * 8a4bdae9cde1e71fdc40f62919cf8e03139e1bf6 - lib: rename util/selinux.h guard due to conflict with selinux.h
  * 8a999ad5e583c9aac906a177fc8e0a441447a796 - lib: add selinux_copy_files_safely
  * 55e02139d0a7e93c6f6834ccc65593f8dbc03c48 - lib: add selinux_mkstemp_copy
  * cf713678bea6168316b14445ea3d57cf125b8c3f - lib: add file_mktmp_copy
  * d1f000fcf543c7b243bb1c093537244f4cb9cb12 - lib: rename textfile_copy to file_copy
  * 0add742394004ade7a5e4bdce279f13302add9d5 - lib: keep selinux context for backed up files
  * ea4a3bf7c31602e9c5147b3be53da9b15bb2c664 - lib: add selinux_file_copy
  * 91c92d77d57ce78d31ed3b6b17893514d6f098c7 - lib: add public functions to list and remove backups
  * d75921877d38131ee87b6df6400fc86165be63a3 - lib: add dir_remove to recursively remove directory
  * cbbea6b29e00661810726a1c0c620e5b0a0c36d8 - lib: put directory listing into its own utility module
  * 63a871303c053170e3a6776cea7c88fc411b134f - lib: backup also valid authselect configuration
  * 9eb34d0d90b94950cc3429e2eecbeb3fa3bc66b6 - lib: put config file name to standalone macro
  * dead5db3860a272e86d0980bd94b49cbdc9d6c32 - lib: refactor backup functionality
  * 73950ee94483a7bf6b2dc08a6fb430471685a739 - lib: use authselect file names for backup
  * 145ff9ef778ba929c4414e2ade97bd64f6e62937 - lib: fix typo in comment
