### ISSUE TITLE
Add a "with-pammount" option to enable "pam-mount"

### ISSUE THREAD

**Issue by JGoutin** [pbrezina/authselect#178]
Currently, to use "pam_mount", it is required to modify `/etc/pam.d/password-auth` (That is not recommended with authselect) or to create a new profile.

A working way to enable *pam_mount* is to add the following line to the top of  `/etc/pam.d/password-auth`:
`auth        required                                     pam_mount.so`

And the following line at the bottom of  `/etc/pam.d/password-auth`
`session     optional                                     pam_mount.so`

I tested this based on _sssd_ profile with success to mount a SMB share. I can eventually propose a PR with this change.

I also find this oldest issues with someone also trying to use  pam_mount and authselect : https://github.com/pbrezina/authselect/issues/52

**Comment by pbrezina** [comment]
Can autofs be used instead of this module?

**Comment by JGoutin** [comment]
`autofs` require to save user credentials in a file (In user home directory or `/etc` configuration files)

`pam_mount` allow tu use user password. This has two advantages over `autofs`:
* This is more secure, because it do not require to have credentials always stored in the file system.
* This is more easier to use it with many user because it no not need to create specific extra credential files for each user.

**Comment by q2dg** [comment]
pam_mount isn't updated from some time ago and it seems a minor project. I would look into systemd's automount/mount units instead (https://blog.agchapman.com/auto-mounting-network-file-systems-with-systemd)

**Comment by pbrezina** [comment]
Sorry this took such long time to answer. I am not an expert to samba shares so I had to do some research and ask few people.

The correct way to mount cifs password-less is via kerberos. For example:
```
$ klist
Ticket cache: FILE:/tmp/krb5cc_863600500_iXJi9x
Default principal: Administrator@AD.VM

Valid starting       Expires              Service principal
11/13/2019 12:20:23  11/13/2019 22:20:23  krbtgt/AD.VM@AD.VM
	renew until 11/20/2019 12:20:23
11/13/2019 12:30:00  11/13/2019 22:20:23  cifs/root-dc.ad.vm@AD.VM
	renew until 11/20/2019 12:20:23

$ sudo mount -t cifs -o user=$USER,cruid=$USER,sec=krb5,vers=3.0,multiuser //root-dc.ad.vm/_shared _shared
```

This can be also converted to autofs map to mount it automatically and use user's credentials and permissions. [See this for example](https://lists.samba.org/archive/samba/2014-September/184796.html).

Since you are using sssd to authenticate as an Windows user you should have Kerberos already working.

>pam_mount isn't updated from some time ago and it seems a minor project. I would look into systemd's automount/mount units instead (https://blog.agchapman.com/auto-mounting-network-file-systems-with-systemd)

systemd mounts are interesting, however (to my best knowledge) it does not support password-less login without storing credentials in a file.

I asked experts on this topic whether this is something that should be supported in authselect upstream. The answer was that the correct way to do this is to use Kerberos and cifs mounts (see above). If NTLM authentication is needed for some reason, some modifications in SSSD and gssproxy are needed but so far there was no desire to implement this. pam_mount is considered to be a workaround instead of a proper solution that breaks whenever the remote filesystem needs to be remounted or reauthenticated.

For these arguments, I must decline this request.

**Comment by JGoutin** [comment]
Thanks for the answer, I will look at this.

**Comment by pbrezina** [comment]
FYI I just wrote an article about this here: https://sssd.io/docs/ad/ad-autofs.html
