### ISSUE TITLE
Add cacertdir_rehash to authselect

### ISSUE THREAD

**Issue by Firstyear** [pbrezina/authselect#27]
Authconfig shipped with a cacertdir_rehash command. This is important for correctly configuring the ldap TLS_CERTDIR, and for a number of other dependencies (python3-lib389 will depend on it).

It would be great to have cacertdir_rehash ported to authselect,

**Comment by pbrezina** [comment]
We talked with Tomáš Mráz (author of authconfig and current maintainer) yesterday about this tool. This script was created at a time were there was no native support in openssl to do this. Now, there is `openssl rehash <directory>` command that does exactly this. It is available since Fedora 26 as part of openssl 1.1.

Please, switch to `openssl rehash`. Since `cacertdir_rehash` calls openssl, it will not bring any new dependency.
