### ISSUE TITLE
Create NIS profile

### ISSUE THREAD

**Issue by pbrezina** [pbrezina/authselect#61]
There are still lot of users using NIS, we should create an authselect profile for this. Compatibility tool should also write yp.conf and perform changes that authconfig would do with its NIS-related options.

**Comment by PatrickBzh** [comment]
I'm very interested in NIS support too

**Comment by sf-pc** [comment]
@pbrezina please do prepare a scratch build. (Presumably it requires a few merges, such as #72.)

**Comment by pbrezina** [comment]
You can find scratch build here: https://koji.fedoraproject.org/koji/taskinfo?taskID=28905681

It is marked as 0.4-4.1 so you can safely downgrade to current authselect release if needed. It is a preview of the 1.0 release as it contains all the new features. Thank you  for testing.

**Comment by pbrezina** [comment]
I pushed the patches to master so I can built up on them. If you find any issues, please reopen.

**Comment by sf-pc** [comment]
Almost!

`/etc/nsswitch.conf` ends up with a combination of the correct NIS profile, and also the default packaged contents (**which breaks NIS**, specifically autofs), ie.

```
# Generated by authselect
...
passwd:     files nis
...
# Included from /etc/authselect/user-nsswitch.conf
...
passwd:      sss files systemd
...
```
[nsswitch.conf.txt](https://github.com/pbrezina/authselect/files/2274680/nsswitch.conf.txt)

The pollution is presumably caused by:
https://github.com/pbrezina/authselect/blob/3f578c34530ae0d622579eec9e7447314eff1771/rpm/authselect.spec.in#L170

Removing those duplicated lines from `/etc/authselect/user-nsswitch.conf` and running `authselect apply-changes` results in a system environment that appears to fully support NIS (ssh, auto-mounting, sudo, gnome, etc). (Note that I also had to apply the fix for the `IPAddressDeny=any` [bug in nss_nis](https://bugzilla.redhat.com/show_bug.cgi?id=1574959).)

Testing involved installing Fedora Server 28 via a kickstart that includes update repos + a repo with your scratch built rpms, and amongst other non-auth things, one of the below lines:
 
`auth --enableshadow --enablemd5 --enablenis --nisdomain=ourdomainhere --passalgo=sha512`
or
`authconfig --update --enableshadow  --passalgo=sha512 --enablenis --nisdomain=ourdomainhere --enablepreferdns --disableldap --disableldapauth --disablesssd --disablesssdauth`
which both produced much the same result.

**Comment by pbrezina** [comment]
Thank you. Duplicate nsswitch maps were supposed to be removed, but somehow the processing of regular expression responsible for it got wrong before pushing the patches.

Here is a new scratch build:
https://koji.fedoraproject.org/koji/taskinfo?taskID=28963900

I contains also fix for https://github.com/pbrezina/authselect/issues/76.
