### ISSUE TITLE
`authconfig --update` unexpectedly resets selected profile

### ISSUE THREAD

**Issue by sf-pc** [pbrezina/authselect#76]
The command is expected to do very little, just updating config to account for changes to external packages, not change the whole auth method!

```
$ cat /etc/authselect/authselect.conf
nis
$ authconfig --update
...
Executing: /usr/bin/authselect select sssd --force
...
$ cat /etc/authselect/authselect.conf
sssd
```

**Comment by pbrezina** [comment]
Thanks. The problem here was that we read `/etc/sysconfig/authconfig` (which store options that were used) but we never updated the options with current configuration. Thus when you called `authconfig --enablenis ... --update` it never stored `USENIS=true` in sysconfig and therefore subsequent run of `authconfig --update` started with outdated settings.
